name: mediezy_user
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+4

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  # ui
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  flutter_iconly: ^1.0.2
  animation_wrappers: ^3.0.0
  card_swiper: ^3.0.1
  easy_date_timeline: ^1.0.2
  http: ^1.1.0
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  fluttertoast: ^8.2.4
  image_picker: ^1.0.5
  file_picker: ^6.1.1
  flutter_pdfview: ^1.3.2
  connectivity_plus: ^5.0.2
  flutter_image_compress: ^2.1.0
  lottie: ^3.0.0
  fancy_shimmer_image: ^2.0.3
  shimmer: ^3.0.0
  share_plus: ^7.2.2
  flutter_barcode_scanner: ^2.0.0
  dio: ^5.4.2+1
  dartz: ^0.10.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  analyzer: ^5.13.0
  freezed_annotation: ^2.4.1
  get_storage: ^2.1.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  get: ^4.6.1
  google_fonts: ^6.2.1
  loading_animation_widget: ^1.2.1
  razorpay_flutter: ^1.3.6
  maps_launcher  : ^2.2.1
  firebase_core: ^2.30.1
  firebase_auth: 
  firebase_analytics: ^10.10.4
  cloud_firestore: ^4.17.3
  google_sign_in: ^6.2.1
  firebase_auth_oauth_platform_interface: ^1.0.3
  
  flutter_facebook_auth: ^6.2.0
  flutter_rating_stars: ^1.1.0
  flutter_rating_bar: ^4.0.1
  flutter_local_notifications: ^17.1.2
  firebase_messaging: ^14.9.2
  sign_in_button: ^3.2.0
  permission_handler: ^11.3.1
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  freezed: ^2.4.7
  injectable_generator: ^1.5.3
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
