name: mediezy_user
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 
version: 1.0.0+3

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ui
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  flutter_iconly: ^1.0.2
  animation_wrappers: ^3.0.0
  card_swiper: ^3.0.1
  easy_date_timeline: ^1.0.2
  http: ^1.1.0
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  fluttertoast: ^8.2.4
  image_picker: ^1.0.5
  file_picker: ^6.1.1
  flutter_pdfview: ^1.3.2
  connectivity_plus: ^5.0.2
  flutter_image_compress: ^2.1.0
  lottie: ^3.0.0
  fancy_shimmer_image: ^2.0.3
  shimmer: ^3.0.0
  share_plus: ^7.2.2
  flutter_barcode_scanner: ^2.0.0
  dio: ^5.4.2+1
  dartz: ^0.10.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  analyzer: ^5.13.0
  freezed_annotation: ^2.4.1
  get_storage: ^2.1.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  get: ^4.6.1
  google_fonts: ^6.2.1
  loading_animation_widget: ^1.2.1
  razorpay_flutter: ^1.3.6
  maps_launcher  : ^2.2.1
  rename: ^3.0.2
  flutter_svg: ^2.0.10+1
  permission_handler: ^10.2.0
  app_links: ^5.0.0
  go_router: ^14.0.2
  
  
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  freezed: ^2.4.7
  injectable_generator: ^1.5.3
  

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
