// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXdwYQQ1C1sbm-rOrr2i6xA9R2j-D7sek',
    appId: '1:220538846317:android:ca4dbc4b5795a0157f5364',
    messagingSenderId: '220538846317',
    projectId: 'mediezy-28594',
    storageBucket: 'mediezy-28594.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRB-DcMcdcL8rJrIDSvQrB6pQbyv2N6Jc',
    appId: '1:220538846317:ios:d9f8cbf0459d286e7f5364',
    messagingSenderId: '220538846317',
    projectId: 'mediezy-28594',
    storageBucket: 'mediezy-28594.appspot.com',
    androidClientId: '220538846317-ce1q4mncb7n193ov8qut8994g2d7974k.apps.googleusercontent.com',
    iosClientId: '220538846317-vnfv89k6tnpcmrpkqm3bn90j1vtd4v2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.mediezyUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRB-DcMcdcL8rJrIDSvQrB6pQbyv2N6Jc',
    appId: '1:220538846317:ios:d9f8cbf0459d286e7f5364',
    messagingSenderId: '220538846317',
    projectId: 'mediezy-28594',
    storageBucket: 'mediezy-28594.appspot.com',
    androidClientId: '220538846317-ce1q4mncb7n193ov8qut8994g2d7974k.apps.googleusercontent.com',
    iosClientId: '220538846317-vnfv89k6tnpcmrpkqm3bn90j1vtd4v2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.mediezyUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIqgdthNZqe2Chb378t--AG82RzqHhTEk',
    appId: '1:220538846317:web:6ad07d56fbc8c9ee7f5364',
    messagingSenderId: '220538846317',
    projectId: 'mediezy-28594',
    authDomain: 'mediezy-28594.firebaseapp.com',
    storageBucket: 'mediezy-28594.appspot.com',
  );

}